# Generated by Django 6.0.6 on 2026-09-03 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_favourite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_quantity', models.IntegerField(blank=True, null=True)),
                ('new_quantity', models.IntegerField()),
                ('action', models.CharField(choices=[('ADDED', 'Added'), ('QUANTITY_INCREASED', 'Quantity Increased'), ('QUANTITY_DECREASED', 'Quantity Decreased'), ('REMOVED', 'Removed')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
